{
 "title": "K8s / Cluster",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Total CPU cores booked",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores)",
     "legendFormat": "cores booked"
    },
    {
     "expr": "100* sum(kube_pod_container_resource_requests_cpu_cores) / sum(kube_node_status_capacity_cpu_cores)",
     "legendFormat": "%"
    }
   ]
  },
  {
   "title": "Total memory bookings",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes)",
     "legendFormat": "memory booked"
    },
    {
     "expr": "100* sum(kube_pod_container_resource_requests_memory_bytes) / sum(kube_node_status_capacity_memory_bytes)",
     "legendFormat": "%"
    }
   ]
  },
  {
   "title": "Cores",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity_cpu_cores)"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity_memory_bytes)/1024/1024/1024"
    }
   ]
  },
  {
   "title": "Load1",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1", "legendFormat": "{{kubernetes_node}}" }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg by (mode) (irate(node_cpu_seconds_total{mode!=\"idle\"}[5m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Pod restarts",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_restarts_total[5m])",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Disk Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_written_bytes_total{mode!=\"idle\"}[5m])",
     "legendFormat": "{{instance_name}}-written"
    },
    {
     "expr": "irate(node_disk_read_bytes_total{mode!=\"idle\"}[5m])",
     "legendFormat": "{{instance_name}}-read"
    }
   ]
  },
  {
   "title": "Disk Iops",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{mode!=\"idle\"}[5m])",
     "legendFormat": "{{instance_name}}-{{device}}-reads"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{mode!=\"idle\"}[5m])",
     "legendFormat": "{{instance_name}}-{{device}}-writes"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{device!~\"lo|bond[0-9]|cbr[0-9]|veth.*|azv.*|cni.*|flannel.*|cal.*|lxc.*\"}[5m])",
     "legendFormat": "{{device}} outbound"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device!~\"lo|bond[0-9]|cbr[0-9]|veth.*|azv.*|cni.*|flannel.*|cal.*|lxc.*\"}[5m])",
     "legendFormat": "{{device}} inbound"
    }
   ]
  },
  {
   "title": "Memory bookings per namespace",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes)  by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "CPU cores booked by namespace",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores)  by (namespace)"
    }
   ]
  },
  {
   "title": "Free memory %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes/node_memory_MemTotal_bytes",
     "legendFormat": "{{kubernetes_node}}"
    }
   ]
  },
  {
   "title": "Persistent Volume Usage - %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes/kubelet_volume_stats_capacity_bytes",
     "legendFormat": "{{namespace}}/{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Disk free space",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100*(min by (mountpoint,instance_name) (node_filesystem_avail_bytes{device=~\"/dev/.*\",}/node_filesystem_size_bytes{device=~\"/dev/.*\"}))",
     "legendFormat": "{{kubernetes_node}}"
    }
   ]
  }
 ]
}